### ISSUE TITLE
Is this provider maintained or planned to be maintained?

### ISSUE THREAD

**Issue by pnancarrow** [rewe-digital/terraform-provider-sonarcloud#143]
### Description

Hey there! First, nice job on this provider and all the supported resources. It appears that there has not been a release in approximately a year, so I was wondering if you have any plans to continue supporting it. Many resources are seeing errors similar to that noted in this issue https://github.com/rewe-digital/terraform-provider-sonarcloud/issues/141 due to API changes. 

I don't want to buy into it if there isn't support and also would consider contributing if I know PRs will be merged and released!

**Comment by renefritze** [comment]
Maybe @reinoudk is the person to answer this?

**Comment by renefritze** [comment]
Maybe @elmarx , @svenjacobs, @pnancarrow or @JanMa can comment?

**Comment by svenjacobs** [comment]
@reinoudk is not working for REWE digital anymore. I myself have nothing to do with Terraform 😉 Maybe another RD colleague wants to take over this repository?

**Comment by svenjacobs** [comment]
I asked around and unfortunately no one is maintaining this repository anymore. It is going to be archived soon. Please fork it if you want to continue developing it.
