### ISSUE TITLE
Projects Permissions and Import

### ISSUE THREAD

**Issue by almssp** [rewe-digital/terraform-provider-sonarcloud#39]
### Description

Project permissions allow to a more granular level of permissions between users and projects would be great to have this covered in the provider.

Also importing data back for integration with and already existent configuration would also be great.

**Comment by almssp** [comment]
https://github.com/rewe-digital/terraform-provider-sonarcloud/pull/40


Import For Group Membership.

**Comment by almssp** [comment]
Hey

No worries. API’s can be a pain when gets updated and changed.
I used some of the documentation to add the multiple attributes in order to allow to Match a group and Login for the import https://www.terraform.io/plugin/framework/resources/import <https://www.terraform.io/plugin/framework/resources/import>

I hope it meets the coding standard you have been using.


Regards
Andre

**Comment by reinoudk** [comment]
The import functionality was done in #40 and released in `v0.2.1`. The project permissions should be added back in #81.
