### ISSUE TITLE
Feature: manage project branches via the provider

### ISSUE THREAD

**Issue by mdb** [rewe-digital/terraform-provider-sonarcloud#99]
### Description

👋 Thanks for your work on `terraform-provider-sonarcloud`. It would be useful if the provider supported the ability to configure/manage [project branches](https://sonarcloud.io/web_api/api/project_branches?deprecated=false). In my case, I'm successfully using the provider to manage projects, yet those projects all cite `master` as the main source code branch, despite that my organization utilizes a default `main` branch (in line with GitHub's own default branch name).

### New or Affected Resource(s)

* It would be helpful if the provider had a `project_main_branch` resource, or something similar

### Potential Terraform Configuration

```tf
resource "sonarcloud_project_main_branch" "main" {
  project_key = "my-project"
  name        = "main"
}
```

**Comment by reinoudk** [comment]
This has been released with [v0.4.0](https://github.com/rewe-digital/terraform-provider-sonarcloud/releases/tag/v0.4.0) ([docs](https://registry.terraform.io/providers/rewe-digital/sonarcloud/latest/docs/resources/project_main_branch)). Thanks for implementing this @mdb!
